<a href="https://colab.research.google.com/github/martinpius/Behind-Keras-Layers-and-Models/blob/main/Sequential_models_in_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
try:
  drive.mount("/content/drive/", force_remount = True)
  COLAB = True
  import tensorflow as tf
  print(f"You are using colab with tensorflow version: {tf.__version__}")
except Exception as e:
  COLAB = False
  print(f"{type(e)}: {e}\n----Load your drive----")


Mounted at /content/drive/
You are using colab with tensorflow version: 2.3.0


In [2]:
import tensorflow as tf
#Sequential keras model can be constructed in multiple ways like as followa

In [3]:
#We can use the add method..Add layer after layer
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape = [100,3], name = 'input'))
model.add(tf.keras.layers.Dense(64, activation = 'relu', name = 'l1'))
model.add(tf.keras.layers.Dense(32, activation = 'relu', name = 'l2'))
model.add(tf.keras.layers.Dense(5, activation = 'softmax', name = 'out'))

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
l1 (Dense)                   (None, 100, 64)           256       
_________________________________________________________________
l2 (Dense)                   (None, 100, 32)           2080      
_________________________________________________________________
out (Dense)                  (None, 100, 5)            165       
Total params: 2,501
Trainable params: 2,501
Non-trainable params: 0
_________________________________________________________________


In [5]:
#We can provide a list of argument to a sequential object
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 64,activation = 'relu', name = 'l1'),
    tf.keras.layers.Dense(units = 32, activation = 'relu', name = 'l2'),
    tf.keras.layers.Dense(units = 5, activation = 'softmax', name = 'out')
])

In [6]:
model = tf.keras.Sequential([
                             tf.keras.layers.Input(shape = [10], name = 'input_layer'),
                             tf.keras.layers.Dense(units = 64, kernel_initializer = 'random_normal', name = 'layer_1'),
                             tf.keras.layers.Activation(tf.nn.relu),
                             tf.keras.layers.Dense(units = 32, kernel_initializer = 'random_normal',name = 'layer_2'),
                             tf.keras.layers.Activation(tf.nn.relu),
                             tf.keras.layers.Dense(units = 5, kernel_initializer = 'random_normal', name = 'layer_3'),
                             tf.keras.layers.Activation(tf.nn.softmax)
])

In [7]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer_1 (Dense)              (None, 64)                704       
_________________________________________________________________
activation (Activation)      (None, 64)                0         
_________________________________________________________________
layer_2 (Dense)              (None, 32)                2080      
_________________________________________________________________
activation_1 (Activation)    (None, 32)                0         
_________________________________________________________________
layer_3 (Dense)              (None, 5)                 165       
_________________________________________________________________
activation_2 (Activation)    (None, 5)                 0         
Total params: 2,949
Trainable params: 2,949
Non-trainable params: 0
____________________________________________________

In [8]:
out = model(tf.ones(shape = (10,10)))

In [9]:
out

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446],
       [0.19916098, 0.20042585, 0.19851448, 0.19996427, 0.20193446]],
      dtype=float32)>

In [10]:
display(model.layers)

In [11]:
#We can also stack layers ontop of each other like as follow
#input = tf.keras.layers.Input(shape = [10,100], name = 'input_shape')
layer1 = tf.keras.layers.Dense(units = 64, kernel_initializer= 'random_normal',name = 'layer_1')
layer2 = tf.keras.layers.Activation(tf.nn.relu)
layer3 = tf.keras.layers.Dense(units = 32, kernel_initializer= 'random_normal', name = 'layer_3')
layer4 = tf.keras.layers.Activation(tf.nn.relu)
layer5 = tf.keras.layers.Dense(units = 4, kernel_initializer = 'random_normal', name = 'output')
layer6 = tf.keras.layers.Activation(tf.nn.softmax)
model = layer6(layer5(layer4(layer3(layer2(layer1(tf.ones(shape = (3,3))))))))

In [12]:
display(model)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.2507821 , 0.24942794, 0.24968003, 0.25010994],
       [0.2507821 , 0.24942794, 0.24968003, 0.25010994],
       [0.2507821 , 0.24942794, 0.24968003, 0.25010994]], dtype=float32)>

In [13]:
#input is actually not a separate kera's layer and therefore we can attach the shape of the input in the first layer like as follow
model = tf.keras.Sequential([
                             tf.keras.layers.Dense(units = 64, kernel_initializer = 'random_normal', name = 'layer_1', input_shape = [10,]),
                             tf.keras.layers.Activation(tf.nn.relu),
                             tf.keras.layers.Dense(units = 32, kernel_initializer = 'random_normal', name = 'layer_2'),
                             tf.keras.layers.Activation(tf.nn.relu),
                             tf.keras.layers.Dense(units = 4, kernel_initializer = 'random_normal', name = 'out'),
                             tf.keras.layers.Activation(tf.nn.softmax)
])

In [14]:
display(model.get_weights)

<bound method Model.get_weights of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7ff021f05240>>

In [15]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer_1 (Dense)              (None, 64)                704       
_________________________________________________________________
activation_6 (Activation)    (None, 64)                0         
_________________________________________________________________
layer_2 (Dense)              (None, 32)                2080      
_________________________________________________________________
activation_7 (Activation)    (None, 32)                0         
_________________________________________________________________
out (Dense)                  (None, 4)                 132       
_________________________________________________________________
activation_8 (Activation)    (None, 4)                 0         
Total params: 2,916
Trainable params: 2,916
Non-trainable params: 0
____________________________________________________

In [16]:
model.layers

In [17]:
#Debugging a sequential model using add() and model.summary() to track the progress step by step
#To demonstrate consider the following image classification sequential model

In [18]:
from tensorflow.keras.layers import Dense, Activation,MaxPooling2D, GlobalMaxPooling2D, BatchNormalization, Conv2D, Input, Dropout

In [19]:
from tensorflow.keras.models import Sequential

In [20]:
model = Sequential()

In [21]:
model.add(Input(shape = (250,250,3), name = 'input'))

In [22]:
model.add(Conv2D(filters = 32, kernel_size = (5,5), strides = (2,2), padding = 'valid'))

In [23]:
model.add(Activation('relu'))

In [24]:
model.add(Conv2D(filters = 32, kernel_size =(5,5), strides = (2,2), padding = 'valid'))
model.add(MaxPooling2D(pool_size = 3))

In [25]:
model.add(BatchNormalization())


In [26]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
activation_9 (Activation)    (None, 123, 123, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 60, 60, 32)        25632     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 20, 20, 32)        0         
_________________________________________________________________
batch_normalization (BatchNo (None, 20, 20, 32)        128       
Total params: 28,192
Trainable params: 28,128
Non-trainable params: 64
_________________________________________________________________


In [27]:
model.add(Conv2D(filters =32, kernel_size = (3,3), strides = (2,2),padding = 'same'))

In [28]:
model.add(Activation('relu'))

In [29]:
model.add(MaxPooling2D(pool_size = 3))

In [30]:
model.add(BatchNormalization())

In [31]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
activation_9 (Activation)    (None, 123, 123, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 60, 60, 32)        25632     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 20, 20, 32)        0         
_________________________________________________________________
batch_normalization (BatchNo (None, 20, 20, 32)        128       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 10, 10, 32)        9248      
_________________________________________________________________
activation_10 (Activation)   (None, 10, 10, 32)       

In [32]:
model.add(Conv2D(filters = 32, kernel_size =(2,2), strides = (1,1), padding = 'same'))

In [33]:
model.add(Activation('relu'))

In [34]:
model.add(BatchNormalization())

In [35]:
model.add(MaxPooling2D(pool_size = (3)))

In [36]:
model.add(GlobalMaxPooling2D())

In [37]:
model.add(Dense(10, activation = 'relu'))

In [38]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
activation_9 (Activation)    (None, 123, 123, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 60, 60, 32)        25632     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 20, 20, 32)        0         
_________________________________________________________________
batch_normalization (BatchNo (None, 20, 20, 32)        128       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 10, 10, 32)        9248      
_________________________________________________________________
activation_10 (Activation)   (None, 10, 10, 32)       

In [39]:
display([layer.output for layer in model.layers])#Displaye all layers in the model.

[<tf.Tensor 'conv2d/BiasAdd:0' shape=(None, 123, 123, 32) dtype=float32>,
 <tf.Tensor 'activation_9/Relu:0' shape=(None, 123, 123, 32) dtype=float32>,
 <tf.Tensor 'conv2d_1/BiasAdd:0' shape=(None, 60, 60, 32) dtype=float32>,
 <tf.Tensor 'max_pooling2d/MaxPool:0' shape=(None, 20, 20, 32) dtype=float32>,
 <tf.Tensor 'batch_normalization/cond/Identity:0' shape=(None, 20, 20, 32) dtype=float32>,
 <tf.Tensor 'conv2d_2/BiasAdd:0' shape=(None, 10, 10, 32) dtype=float32>,
 <tf.Tensor 'activation_10/Relu:0' shape=(None, 10, 10, 32) dtype=float32>,
 <tf.Tensor 'max_pooling2d_1/MaxPool:0' shape=(None, 3, 3, 32) dtype=float32>,
 <tf.Tensor 'batch_normalization_1/cond/Identity:0' shape=(None, 3, 3, 32) dtype=float32>,
 <tf.Tensor 'conv2d_3/BiasAdd:0' shape=(None, 3, 3, 32) dtype=float32>,
 <tf.Tensor 'activation_11/Relu:0' shape=(None, 3, 3, 32) dtype=float32>,
 <tf.Tensor 'batch_normalization_2/cond/Identity:0' shape=(None, 3, 3, 32) dtype=float32>,
 <tf.Tensor 'max_pooling2d_2/MaxPool:0' shape=(N

In [40]:
#Sample Model to reuse
model = Sequential([Input(shape = (250,250,3)),
Conv2D(filters = 32, kernel_size = (5,5),strides = (2,2),padding = 'same',activation = 'relu'),
Conv2D(filters = 32, kernel_size = (3,3), strides = (2,2), padding = 'same', activation = 'relu'),
BatchNormalization(),
Dropout(rate = 0.2),
MaxPooling2D(pool_size = 3),
Conv2D(filters = 32, kernel_size = (3,3), strides = (1,1),padding = 'valid', activation = 'relu'),
])
#Extracts features from the above model and reuse it in another keras model
fetures = tf.keras.Model(inputs = model.inputs, outputs = [layer.output for layer in model.layers])

In [41]:
display(fetures)

In [42]:
input_test = tf.ones((100, 250,250,3))


In [43]:
#Call our feature's extract
fetures(input_test)

[<tf.Tensor: shape=(100, 125, 125, 32), dtype=float32, numpy=
 array([[[[0.37051272, 0.6801586 , 0.        , ..., 0.        ,
           0.84082747, 0.        ],
          [0.5793271 , 0.73480535, 0.        , ..., 0.        ,
           0.7300581 , 0.        ],
          [0.5793271 , 0.73480535, 0.        , ..., 0.        ,
           0.7300581 , 0.        ],
          ...,
          [0.5793271 , 0.73480535, 0.        , ..., 0.        ,
           0.7300581 , 0.        ],
          [0.5793271 , 0.73480535, 0.        , ..., 0.        ,
           0.7300581 , 0.        ],
          [0.5394089 , 0.75244874, 0.        , ..., 0.        ,
           0.1594953 , 0.04195287]],
 
         [[0.        , 0.7521603 , 0.        , ..., 0.        ,
           0.55174196, 0.        ],
          [0.221947  , 0.77052283, 0.        , ..., 0.        ,
           0.43198022, 0.        ],
          [0.221947  , 0.77052283, 0.        , ..., 0.        ,
           0.43198022, 0.        ],
          ...,
     

In [44]:
#Feature extraction from a specified layer
model = Sequential([
                    Input(shape = (128,128,3), name = 'input_shape'),
                    Conv2D(filters = 32, kernel_size = (5,5), strides = (2,2), padding = 'same', activation = 'relu', name = 'first_layer'),
                    Conv2D(filters = 32, kernel_size = (3,3), strides = (1,1), padding = 'same', activation ='relu', name = 'second_layer'),
                    BatchNormalization(),
                    MaxPooling2D(pool_size = 3),
                    Dropout(rate = 0.2),
          
])

In [45]:
feat_spec_extract = tf.keras.Model(
    inputs = model.inputs, outputs = model.get_layer(name = 'second_layer').output
)

In [46]:
#Call the extract_spec above
feat_spec_extract(tf.ones(shape = (2,250,250,3)))

<tf.Tensor: shape=(2, 125, 125, 32), dtype=float32, numpy=
array([[[[0.00558592, 0.16841039, 0.        , ..., 0.05149705,
          0.1223728 , 0.        ],
         [0.02781567, 0.14233774, 0.        , ..., 0.06275443,
          0.        , 0.        ],
         [0.00296225, 0.15307905, 0.00460803, ..., 0.01807701,
          0.        , 0.        ],
         ...,
         [0.00296225, 0.15307905, 0.00460803, ..., 0.01807701,
          0.        , 0.        ],
         [0.        , 0.13618988, 0.02339599, ..., 0.        ,
          0.        , 0.01497465],
         [0.        , 0.0329588 , 0.03705248, ..., 0.        ,
          0.        , 0.05571911]],

        [[0.2711386 , 0.16126125, 0.        , ..., 0.08101118,
          0.        , 0.        ],
         [0.32844293, 0.09811858, 0.        , ..., 0.10663766,
          0.        , 0.        ],
         [0.32595366, 0.1390866 , 0.        , ..., 0.04144288,
          0.        , 0.        ],
         ...,
         [0.32595366, 0.13908

In [48]:
##The above procedure of feature's extraction is a good step towards transfer learning in keras sequential models
#A simple architecture of a transfer learning
#Load model
mymodel = tf.keras.applications.InceptionV3(weights= 'imagenet',pooling = 'max', include_top = False)


87916544/87910968 [==============================] - 4s 0us/step


In [49]:
#Freeze the model to prevent any weights incoviniences
mymodel.trainable = False

#You can now apply keras sequential archtecture to create classification model of your choice like as follow:
model = tf.keras.Sequential([
                             mymodel,
                             tf.keras.layers.Dense(units = 10, activation='softmax')
                    ])

In [51]:
mymodel.summary()

Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, None, None,  0                                            
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, None, None, 3 864         input_2[0][0]                    
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (None, None, None, 3 96          conv2d_7[0][0]                   
__________________________________________________________________________________________________
activation_12 (Activation)      (None, None, None, 3 0           batch_normalization_5[0][0]      
_______________________________________________________________________________________

In [52]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inception_v3 (Functional)    (None, 2048)              21802784  
_________________________________________________________________
dense_1 (Dense)              (None, 10)                20490     
Total params: 21,823,274
Trainable params: 20,490
Non-trainable params: 21,802,784
_________________________________________________________________


In [ ]:
#Keras functional API architecture:
